### ISSUE TITLE
Popup should keept opened in some cases

### ISSUE THREAD

**Issue by Amerlander** [roycdaviesuoa/svelte-fomantic-ui#1]
In some situations the popup should kept open, when the mouse moves on top of the popup.

See flowing popup and popup menu:
https://fomantic-ui.com/modules/popup.html#flowing
https://fomantic-ui.com/collections/menu.html#popup-menu

Both are closing to fast in svelte-fomantic-ui

**Comment by roycdaviesuoa** [comment]
First, this is the first feedback I've had - so welcome...  The problem seems to stem from the fact that the default popup settings are not what are being used on the demo page.  That said, a slight tweak would certainly be beneficial.
